name: Github Pages Deploy

on:
   merge_group:
    branches: [ main ]
       
jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [15.x]
    
    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Install and build
        run: npm install && npm run build
      
      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@4.1.1
        with:
          branch: gh-pages # The branch the action should deploy to.
          folder: build # The folder the action should deploy.     

      # Send Mail+
      - name: Send email
        uses: devellany/send-mailer@v1.0.2
        with:
          host: smtp.gmail.com
          port: 465
          account: ${{secrets.ACCOUNT}}
          password: ${{secrets.MAIL_PASSWORD}}
          from: ${{secrets.ACCOUNT}}
          to: ${{secrets.ACCOUNT}}
          subject: Grupo 05
          body: Mensaje automatico al desplegar

